# In all environments, the following files are loaded if they exist,
# the latter taking precedence over the former:
#
#  * .env                contains default values for the environment variables needed by the app
#  * .env.local          uncommitted file with local overrides
#  * .env.$APP_ENV       committed environment-specific defaults
#  * .env.$APP_ENV.local uncommitted environment-specific overrides
#
# Real environment variables win over .env files.
#
# DO NOT DEFINE PRODUCTION SECRETS IN THIS FILE NOR IN ANY OTHER COMMITTED FILES.
# https://symfony.com/doc/current/configuration/secrets.html
#
# Run "composer dump-env prod" to compile .env files for production use (requires symfony/flex >=1.2).
# https://symfony.com/doc/current/best_practices.html#use-environment-variables-for-infrastructure-configuration

###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=
###< symfony/framework-bundle ###

###> symfony/routing ###
# Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
# See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
DEFAULT_URI=https://rent-manager.infinityfreeapp.com
###< symfony/routing ###
DATABASE_LOGIN='if0_40812161'
DATABASE_PWD='ieAr39E5320'
DATABASE_NAME='if0_40812161_rent_manager'
DATABASE_HOSTNAME='sql303.infinityfree.com'
DATABASE_URL="mysql://${DATABASE_LOGIN}:${DATABASE_PWD}@${DATABASE_HOSTNAME}:3306/${DATABASE_NAME}?serverVersion=10.11.2-MariaDB&charset=utf8mb4"
# DATABASE_URL="postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=16&charset=utf8"
###< doctrine/doctrine-bundle ###
###> doctrine/doctrine-bundle ###
# Format described at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# IMPORTANT: You MUST configure your server version, either here or in config/packages/doctrine.yaml
#
# DATABASE_URL="sqlite:///%kernel.project_dir%/var/data_%kernel.environment%.db"
# DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=10.11.2-MariaDB&charset=utf8mb4"
# DATABASE_URL="postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=16&charset=utf8"
###< doctrine/doctrine-bundle ###

###> nelmio/cors-bundle ###
CORS_ALLOW_ORIGIN='^https?://(rent-manager.infinityfreeapp.com|127\.0\.0\.1)(:[0-9]+)?$'
###< nelmio/cors-bundle ###

###> lexik/jwt-authentication-bundle ###
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=33942c4ce4d503acadc43a2fd59e62b2673cfd084ec6a827648b0bc0fa7c9142
###< lexik/jwt-authentication-bundle ###

FRONTEND_URL=https://rent-manager.infinityfreeapp.com
###> knpuniversity/oauth2-client-bundle ###
OAUTH_GOOGLE_CLIENT_ID=550137198068-6k67v075buj2sdv9btfuu38n68fr04fo.apps.googleusercontent.com
OAUTH_GOOGLE_CLIENT_SECRET=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
###< knpuniversity/oauth2-client-bundle ###
###> symfony/mailer ###

MAILER_DSN=smtp://smtp.free.fr:25?encryption=tls&auth_mode=login&username=v39france@free.fr&password=9x2Z[]4j3T]Hge
MAILER_FROM=noreply@rentmanager.fr
###< symfony/mailer ###
